// SS Wayfarer — Procedural Texture Library
// All textures generated by canvas at page load, stored in window.TEX.
// Load this BEFORE aframe.min.js so textures are ready in the loaded handler.
(function () {
  function mkc(w, h) {
    var c = document.createElement('canvas');
    c.width = w; c.height = h;
    return c;
  }

  // ── Metal Wall Panels (512×512) — 4×4 grid ──────────────────────────────
  function metalPanel() {
    var c = mkc(512, 512), x = c.getContext('2d');
    x.fillStyle = '#17181f'; x.fillRect(0, 0, 512, 512);
    for (var r = 0; r < 4; r++) {
      for (var col = 0; col < 4; col++) {
        var px = col * 128, py = r * 128;
        var v = (Math.random() * 12 | 0) - 6, b = 25 + v;
        x.fillStyle = 'rgb(' + b + ',' + b + ',' + (b + 9) + ')';
        x.fillRect(px + 4, py + 4, 120, 120);
        x.fillStyle = 'rgba(88,92,116,0.2)';
        x.fillRect(px + 4, py + 4, 120, 2);
        x.fillRect(px + 4, py + 4, 2, 120);
        x.fillStyle = 'rgba(0,0,0,0.38)';
        x.fillRect(px + 4, py + 122, 120, 2);
        x.fillRect(px + 122, py + 4, 2, 120);
        x.fillStyle = '#06070d';
        x.fillRect(px, py, 128, 4);
        x.fillRect(px, py + 4, 4, 124);
        [[px+12,py+12],[px+116,py+12],[px+12,py+116],[px+116,py+116]].forEach(function(rv) {
          x.beginPath(); x.arc(rv[0], rv[1], 4, 0, Math.PI * 2);
          x.fillStyle = '#05060b'; x.fill();
          x.beginPath(); x.arc(rv[0] - 1.5, rv[1] - 1.5, 2, 0, Math.PI * 2);
          x.fillStyle = 'rgba(82,88,114,0.55)'; x.fill();
        });
      }
    }
    for (var i = 0; i < 2500; i++) {
      x.fillStyle = 'rgba(0,0,0,' + (Math.random() * 0.065) + ')';
      x.fillRect(Math.random() * 512, Math.random() * 512, 2, 1);
    }
    for (var s = 0; s < 16; s++) {
      x.strokeStyle = 'rgba(52,58,76,' + (Math.random() * 0.09) + ')';
      x.lineWidth = 1; x.beginPath();
      var sx = Math.random() * 440, sy = Math.random() * 512;
      x.moveTo(sx, sy); x.lineTo(sx + 30 + Math.random() * 80, sy + (Math.random() - 0.5) * 2);
      x.stroke();
    }
    return c.toDataURL();
  }

  // ── Floor Grating (256×256) ─────────────────────────────────────────────
  function floorGrate() {
    var c = mkc(256, 256), x = c.getContext('2d');
    x.fillStyle = '#0c0d11'; x.fillRect(0, 0, 256, 256);
    x.strokeStyle = '#1e2028'; x.lineWidth = 2;
    for (var i = 0; i <= 256; i += 32) {
      x.beginPath(); x.moveTo(i, 0); x.lineTo(i, 256); x.stroke();
      x.beginPath(); x.moveTo(0, i); x.lineTo(256, i); x.stroke();
    }
    x.strokeStyle = '#161720'; x.lineWidth = 0.9;
    for (var col = 0; col < 8; col++) {
      for (var row = 0; row < 8; row++) {
        var bx = col * 32 + 3, by = row * 32 + 3;
        x.beginPath(); x.moveTo(bx, by + 26); x.lineTo(bx + 26, by); x.stroke();
        x.beginPath(); x.moveTo(bx, by); x.lineTo(bx + 26, by + 26); x.stroke();
      }
    }
    x.strokeStyle = 'rgba(36,40,56,0.38)'; x.lineWidth = 1;
    for (var j = 0; j <= 256; j += 32) {
      x.beginPath(); x.moveTo(j + 1, 0); x.lineTo(j + 1, 256); x.stroke();
      x.beginPath(); x.moveTo(0, j + 1); x.lineTo(256, j + 1); x.stroke();
    }
    return c.toDataURL();
  }

  // ── Ceiling Panels (512×512) — darker ───────────────────────────────────
  function ceilPanel() {
    var c = mkc(512, 512), x = c.getContext('2d');
    x.fillStyle = '#0e0e15'; x.fillRect(0, 0, 512, 512);
    for (var r = 0; r < 4; r++) {
      for (var col = 0; col < 4; col++) {
        var px = col * 128, py = r * 128;
        var v = (Math.random() * 8 | 0) - 4, b = 17 + v;
        x.fillStyle = 'rgb(' + b + ',' + b + ',' + (b + 5) + ')';
        x.fillRect(px + 3, py + 3, 122, 122);
        x.fillStyle = '#050508';
        x.fillRect(px, py, 128, 3);
        x.fillRect(px, py + 3, 3, 125);
        [[px+10,py+10],[px+118,py+10],[px+10,py+118],[px+118,py+118]].forEach(function(rv) {
          x.beginPath(); x.arc(rv[0], rv[1], 2.5, 0, Math.PI * 2);
          x.fillStyle = '#040506'; x.fill();
        });
      }
    }
    return c.toDataURL();
  }

  // ── Star Field Sky (equirectangular 1024×512) ────────────────────────────
  function starfield() {
    var c = mkc(1024, 512), x = c.getContext('2d');
    x.fillStyle = '#000008'; x.fillRect(0, 0, 1024, 512);
    [{x:210,y:145,r:195,rgb:'8,3,22',a:0.52},{x:700,y:200,r:215,rgb:'3,8,22',a:0.46},
     {x:480,y:368,r:155,rgb:'12,3,9',a:0.40},{x:880,y:118,r:165,rgb:'4,11,8',a:0.36},
     {x:130,y:398,r:128,rgb:'10,2,4',a:0.33},{x:600,y:58,r:108,rgb:'5,4,14',a:0.30}
    ].forEach(function(n) {
      var p = n.rgb.split(',');
      var gr = x.createRadialGradient(n.x, n.y, 0, n.x, n.y, n.r);
      gr.addColorStop(0, 'rgba(' + p[0] + ',' + p[1] + ',' + p[2] + ',' + n.a + ')');
      gr.addColorStop(1, 'rgba(0,0,0,0)');
      x.fillStyle = gr; x.fillRect(0, 0, 1024, 512);
    });
    for (var i = 0; i < 3000; i++) {
      var sx = Math.random() * 1024, sy = Math.random() * 512;
      var br = 0.25 + Math.random() * 0.75, t = Math.random();
      var col = t < 0.12 ? 'rgba(170,190,255,' + br + ')' :
                t < 0.20 ? 'rgba(255,210,170,' + br + ')' : 'rgba(255,255,255,' + br + ')';
      var sr = t < 0.85 ? 0.5 : t < 0.95 ? 1.0 : 1.5;
      x.beginPath(); x.arc(sx, sy, sr, 0, Math.PI * 2);
      x.fillStyle = col; x.fill();
    }
    for (var j = 0; j < 14; j++) {
      var fx = Math.random() * 1024, fy = Math.random() * 512;
      var fl = 4 + Math.random() * 10, fa = 0.3 + Math.random() * 0.4;
      x.strokeStyle = 'rgba(255,255,255,' + fa + ')'; x.lineWidth = 0.7;
      x.beginPath(); x.moveTo(fx - fl, fy); x.lineTo(fx + fl, fy); x.stroke();
      x.beginPath(); x.moveTo(fx, fy - fl); x.lineTo(fx, fy + fl); x.stroke();
      x.beginPath(); x.arc(fx, fy, 1.8, 0, Math.PI * 2);
      x.fillStyle = 'rgba(255,255,255,0.95)'; x.fill();
    }
    return c.toDataURL();
  }

  // ── Viewport / Window Space Scene (512×256) ─────────────────────────────
  function viewport() {
    var c = mkc(512, 256), x = c.getContext('2d');
    x.fillStyle = '#000410'; x.fillRect(0, 0, 512, 256);
    var gr = x.createRadialGradient(390, 78, 0, 390, 78, 68);
    gr.addColorStop(0, '#2e1b08'); gr.addColorStop(0.55, '#1a0d04');
    gr.addColorStop(0.85, '#0a0602'); gr.addColorStop(1, 'rgba(0,0,0,0)');
    x.fillStyle = gr; x.fillRect(0, 0, 512, 256);
    x.strokeStyle = 'rgba(40,25,8,0.7)'; x.lineWidth = 4;
    x.beginPath(); x.ellipse(390, 78, 108, 21, -0.3, 0, Math.PI * 2); x.stroke();
    var ng = x.createRadialGradient(80, 178, 0, 80, 178, 118);
    ng.addColorStop(0, 'rgba(8,3,18,0.5)'); ng.addColorStop(1, 'rgba(0,0,0,0)');
    x.fillStyle = ng; x.fillRect(0, 0, 512, 256);
    for (var i = 0; i < 400; i++) {
      var sx = Math.random() * 512, sy = Math.random() * 256;
      var br = 0.35 + Math.random() * 0.65, t = Math.random();
      var col = t < 0.15 ? 'rgba(180,200,255,' + br + ')' :
                t < 0.22 ? 'rgba(255,215,180,' + br + ')' : 'rgba(255,255,255,' + br + ')';
      x.beginPath(); x.arc(sx, sy, t < 0.8 ? 0.6 : 1.2, 0, Math.PI * 2);
      x.fillStyle = col; x.fill();
    }
    [{x:120,y:60,l:6},{x:280,y:140,l:4},{x:460,y:200,l:5}].forEach(function(f) {
      x.strokeStyle = 'rgba(255,255,255,0.38)'; x.lineWidth = 0.7;
      x.beginPath(); x.moveTo(f.x - f.l, f.y); x.lineTo(f.x + f.l, f.y); x.stroke();
      x.beginPath(); x.moveTo(f.x, f.y - f.l); x.lineTo(f.x, f.y + f.l); x.stroke();
      x.beginPath(); x.arc(f.x, f.y, 1.5, 0, Math.PI * 2); x.fillStyle = '#fff'; x.fill();
    });
    var vig = x.createRadialGradient(256, 128, 60, 256, 128, 256);
    vig.addColorStop(0, 'rgba(0,0,0,0)'); vig.addColorStop(1, 'rgba(0,0,5,0.6)');
    x.fillStyle = vig; x.fillRect(0, 0, 512, 256);
    return c.toDataURL();
  }

  // ── Hazard / Warning Stripe (256×32) ────────────────────────────────────
  function warnStripe() {
    var c = mkc(256, 32), x = c.getContext('2d');
    for (var i = 0; i < 8; i++) {
      x.fillStyle = i % 2 === 0 ? '#e8b800' : '#0a0a0a';
      x.fillRect(i * 32, 0, 32, 32);
    }
    x.fillStyle = 'rgba(0,0,0,0.35)';
    x.fillRect(0, 0, 256, 5); x.fillRect(0, 27, 256, 5);
    return c.toDataURL();
  }

  window.TEX = {
    metalPanel : metalPanel(),
    floorGrate : floorGrate(),
    ceilPanel  : ceilPanel(),
    starfield  : starfield(),
    viewport   : viewport(),
    warnStripe : warnStripe(),
  };
}());
